import { Capacitor } from "@capacitor/core";
import { SecureStorage } from "@aparajita/capacitor-secure-storage";

/**
 * PHASE 5A.2 - "4. CRÉER UN ADAPTER UNIQUE".
 *
 * The ONLY place in the shell that knows which secure-storage plugin is
 * used. Everything else calls saveMobileAccessToken/getMobileAccessToken/
 * removeMobileAccessToken and never imports @aparajita/capacitor-secure-
 * storage or Capacitor directly for this purpose - swapping the underlying
 * plugin later (e.g. a different vendor, or adding iOS-specific tuning)
 * never requires touching any other file.
 *
 * Plugin chosen: @aparajita/capacitor-secure-storage@8.0.0 (see this
 * task's own report for the compatibility audit). On Android it encrypts
 * with a key generated by the Android KeyStore (AES-GCM) before writing to
 * SharedPreferences; on iOS it uses the system Keychain.
 *
 * CRITICAL: this plugin's OWN web implementation stores data UNENCRYPTED in
 * localStorage ("for debugging purposes only" per its own README) - using
 * it on the web would silently violate "5. NATIVE VS WEB" (never persist
 * the token in the browser). So the web path here never calls the plugin at
 * all - only an in-memory variable, lost on reload, which is the explicitly
 * accepted behavior for web/dev testing.
 */

const STORAGE_KEY = "comdis_driver_access_token";

let webMemoryToken: string | null = null;

function isNativePlatform(): boolean {
  return Capacitor.isNativePlatform();
}

export async function saveMobileAccessToken(token: string): Promise<void> {
  if (!isNativePlatform()) {
    webMemoryToken = token;
    return;
  }
  await SecureStorage.setItem(STORAGE_KEY, token);
}

export async function getMobileAccessToken(): Promise<string | null> {
  if (!isNativePlatform()) {
    return webMemoryToken;
  }
  try {
    return await SecureStorage.getItem(STORAGE_KEY);
  } catch {
    // A missing key, or a genuine OS/keystore error - either way, no usable
    // token. Never throws up to the caller: "no token" is always a valid,
    // expected outcome (see this module's callers - the boot sequence and
    // logout both treat null as ordinary, not exceptional).
    return null;
  }
}

export async function removeMobileAccessToken(): Promise<void> {
  if (!isNativePlatform()) {
    webMemoryToken = null;
    return;
  }
  try {
    await SecureStorage.removeItem(STORAGE_KEY);
  } catch {
    // Already absent, or an OS error - removal must always look like it
    // succeeded to the caller (matches the server-side revokeSessionByToken
    // contract: logout must never appear to fail).
  }
}
