import type {
  AccountClass,
  AccountType,
  AccountingAccount,
} from "@/types/accounting-account";

export const accountClasses: { classe: AccountClass; label: AccountType }[] = [
  { classe: 1, label: "Comptes de financement permanent" },
  { classe: 2, label: "Comptes d'actif immobilisé" },
  { classe: 3, label: "Comptes d'actif circulant (hors trésorerie)" },
  { classe: 4, label: "Comptes de passif circulant (hors trésorerie)" },
  { classe: 5, label: "Comptes de trésorerie" },
  { classe: 6, label: "Comptes de charges" },
  { classe: 7, label: "Comptes de produits" },
  { classe: 8, label: "Comptes de résultats" },
  { classe: 9, label: "Comptes de produits et charges réfléchis" },
  { classe: 0, label: "Comptes spéciaux" },
];

export function accountTypeLabel(classe: AccountClass): AccountType {
  return accountClasses.find((entry) => entry.classe === classe)!.label;
}

export const accountingAccounts: AccountingAccount[] = [
  {
    id: "acc-1",
    numeroCompte: "1111",
    nomCompte: "Capital social",
    classe: 1,
    typeCompte: accountTypeLabel(1),
    actif: true,
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-01-05"),
  },
  {
    id: "acc-2",
    numeroCompte: "1140",
    nomCompte: "Réserve légale",
    classe: 1,
    typeCompte: accountTypeLabel(1),
    actif: true,
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-06-10"),
  },
  {
    id: "acc-3",
    numeroCompte: "2111",
    nomCompte: "Terrains",
    classe: 2,
    typeCompte: accountTypeLabel(2),
    actif: true,
    createdAt: new Date("2026-01-08"),
    updatedAt: new Date("2026-01-08"),
  },
  {
    id: "acc-4",
    numeroCompte: "2182",
    nomCompte: "Matériel de transport",
    classe: 2,
    typeCompte: accountTypeLabel(2),
    actif: true,
    createdAt: new Date("2026-01-08"),
    updatedAt: new Date("2026-05-14"),
  },
  {
    id: "acc-5",
    numeroCompte: "2331",
    nomCompte: "Matériel informatique",
    classe: 2,
    typeCompte: accountTypeLabel(2),
    actif: true,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-01-10"),
  },
  {
    id: "acc-6",
    numeroCompte: "3111",
    nomCompte: "Marchandises",
    classe: 3,
    typeCompte: accountTypeLabel(3),
    actif: true,
    createdAt: new Date("2026-01-12"),
    updatedAt: new Date("2026-07-01"),
  },
  {
    id: "acc-7",
    numeroCompte: "3421",
    nomCompte: "Clients",
    classe: 3,
    typeCompte: accountTypeLabel(3),
    actif: true,
    createdAt: new Date("2026-01-12"),
    updatedAt: new Date("2026-07-20"),
  },
  {
    id: "acc-8",
    numeroCompte: "3455",
    nomCompte: "État - TVA récupérable",
    classe: 3,
    typeCompte: accountTypeLabel(3),
    actif: true,
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-01-15"),
  },
  {
    id: "acc-9",
    numeroCompte: "4411",
    nomCompte: "Fournisseurs",
    classe: 4,
    typeCompte: accountTypeLabel(4),
    actif: true,
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-07-18"),
  },
  {
    id: "acc-10",
    numeroCompte: "4432",
    nomCompte: "Rémunérations dues au personnel",
    classe: 4,
    typeCompte: accountTypeLabel(4),
    actif: true,
    createdAt: new Date("2026-01-18"),
    updatedAt: new Date("2026-01-18"),
  },
  {
    id: "acc-11",
    numeroCompte: "4455",
    nomCompte: "État - TVA facturée",
    classe: 4,
    typeCompte: accountTypeLabel(4),
    actif: true,
    createdAt: new Date("2026-01-18"),
    updatedAt: new Date("2026-01-18"),
  },
  {
    id: "acc-12",
    numeroCompte: "5111",
    nomCompte: "Banque",
    classe: 5,
    typeCompte: accountTypeLabel(5),
    actif: true,
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-07-25"),
  },
  {
    id: "acc-13",
    numeroCompte: "5161",
    nomCompte: "Caisse",
    classe: 5,
    typeCompte: accountTypeLabel(5),
    actif: true,
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-07-25"),
  },
  {
    id: "acc-14",
    numeroCompte: "6111",
    nomCompte: "Achats de marchandises",
    classe: 6,
    typeCompte: accountTypeLabel(6),
    actif: true,
    createdAt: new Date("2026-01-20"),
    updatedAt: new Date("2026-07-10"),
  },
  {
    id: "acc-15",
    numeroCompte: "6125",
    nomCompte: "Achats de fournitures non stockables",
    classe: 6,
    typeCompte: accountTypeLabel(6),
    actif: true,
    createdAt: new Date("2026-01-20"),
    updatedAt: new Date("2026-01-20"),
  },
  {
    id: "acc-16",
    numeroCompte: "6171",
    nomCompte: "Rémunérations du personnel",
    classe: 6,
    typeCompte: accountTypeLabel(6),
    actif: false,
    createdAt: new Date("2026-01-20"),
    updatedAt: new Date("2026-03-02"),
  },
  {
    id: "acc-17",
    numeroCompte: "7121",
    nomCompte: "Ventes de marchandises",
    classe: 7,
    typeCompte: accountTypeLabel(7),
    actif: true,
    createdAt: new Date("2026-01-22"),
    updatedAt: new Date("2026-07-28"),
  },
  {
    id: "acc-18",
    numeroCompte: "7127",
    nomCompte: "Ventes et produits accessoires",
    classe: 7,
    typeCompte: accountTypeLabel(7),
    actif: true,
    createdAt: new Date("2026-01-22"),
    updatedAt: new Date("2026-01-22"),
  },
  {
    id: "acc-19",
    numeroCompte: "8100",
    nomCompte: "Résultat d'exploitation",
    classe: 8,
    typeCompte: accountTypeLabel(8),
    actif: false,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-02-01"),
  },
  {
    id: "acc-20",
    numeroCompte: "9111",
    nomCompte: "Charges de la comptabilité analytique",
    classe: 9,
    typeCompte: accountTypeLabel(9),
    actif: false,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-02-01"),
  },
  {
    id: "acc-21",
    numeroCompte: "0111",
    nomCompte: "Engagements de financement obtenus",
    classe: 0,
    typeCompte: accountTypeLabel(0),
    actif: true,
    createdAt: new Date("2026-02-05"),
    updatedAt: new Date("2026-02-05"),
  },
];
