import type { Customer } from "@/types/customer";

export const defaultCustomerId = "client-comptoir";

export const customers: Customer[] = [
  {
    id: "client-comptoir",
    nom: "Client Comptoir",
    code: "CLI-0001",
    telephone: "+212 6 00-00-00-00",
    adresse: "Depot principal",
    ville: "Casablanca",
    type: "client_comptoir",
    statut: "actif",
    plafondCredit: 0,
    creditUtilise: 0,
    createdByUserId: "user-admin",
    createdByUserName: "Administrateur COMDIS",
    creationOrigin: "ADMIN",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "client-1",
    nom: "Epicerie El Fath",
    code: "CLI-0002",
    telephone: "+212 6 11-22-33-44",
    adresse: "Rue 12, Hay Mohammadi",
    ville: "Casablanca",
    type: "epicerie",
    statut: "actif",
    email: "contact@elfath.ma",
    contactPrincipal: "Hassan El Fath",
    plafondCredit: 5000,
    creditUtilise: 1200,
    createdByUserId: "user-admin",
    createdByUserName: "Administrateur COMDIS",
    creationOrigin: "ADMIN",
    createdAt: new Date("2026-01-12"),
    updatedAt: new Date("2026-07-20"),
  },
  {
    id: "client-2",
    nom: "Superette Al Amal",
    code: "CLI-0003",
    telephone: "+212 6 22-33-44-55",
    adresse: "Avenue Hassan II",
    ville: "Rabat",
    type: "supermarche",
    statut: "actif",
    plafondCredit: 8000,
    creditUtilise: 2800,
    createdByUserId: "driver-1",
    createdByUserName: "Youssef Amrani",
    createdByDriverId: "driver-1",
    createdFromTruckId: "truck-1",
    createdFromTourId: "tour-truck-1-active",
    creationOrigin: "DRIVER",
    createdAt: new Date("2026-03-05"),
    updatedAt: new Date("2026-07-15"),
  },
  {
    id: "client-3",
    nom: "Grossiste Ben Ali",
    code: "CLI-0004",
    telephone: "+212 6 33-44-55-66",
    adresse: "Marche de gros, lot 18",
    ville: "Marrakech",
    type: "grossiste",
    statut: "bloque",
    plafondCredit: 15000,
    creditUtilise: 14900,
    notes: "Compte bloque en attente de regularisation.",
    createdByUserId: "user-admin",
    createdByUserName: "Administrateur COMDIS",
    creationOrigin: "ADMIN",
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-07-01"),
  },
  {
    id: "client-4",
    nom: "Magasin Nour",
    code: "CLI-0005",
    telephone: "+212 6 44-55-66-77",
    adresse: "Boulevard Zerktouni",
    ville: "Casablanca",
    type: "epicerie",
    statut: "inactif",
    plafondCredit: 3000,
    creditUtilise: 0,
    createdByUserId: "driver-1",
    createdByUserName: "Youssef Amrani",
    createdByDriverId: "driver-1",
    createdFromTruckId: "truck-1",
    createdFromTourId: "tour-truck-1-active",
    creationOrigin: "DRIVER",
    createdAt: new Date("2026-04-18"),
    updatedAt: new Date("2026-06-30"),
  },
];
