import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "prod-1",
    reference: "NIKE-AM90-BLK",
    codeBarres: "3600550100011",
    designation: "Nike Air Max 90",
    categorieId: "cat-chaussures",
    fournisseurId: "fournisseur-sportidis",
    marqueId: "marque-nike",
    prixAchatHT: 65,
    prixAchatTTC: 78,
    prixVenteDetail: 129.99,
    prixVenteDemiGros: 115,
    prixVenteGros: 99,
    tauxTVA: 20,
    quantiteStock: 42,
    stockAlerte: 10,
    unite: "paire",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 6,
    pointsFidelite: 13,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-01-12"),
    updatedAt: new Date("2026-07-20"),
  },
  {
    id: "prod-2",
    reference: "NIKE-PEG40-BLU",
    codeBarres: "3600550100012",
    designation: "Nike Air Zoom Pegasus 40",
    categorieId: "cat-chaussures",
    fournisseurId: "fournisseur-sportidis",
    marqueId: "marque-nike",
    prixAchatHT: 58,
    prixAchatTTC: 69.6,
    prixVenteDetail: 119.99,
    prixVenteDemiGros: 105,
    prixVenteGros: 92,
    tauxTVA: 20,
    quantiteStock: 30,
    stockAlerte: 8,
    unite: "paire",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 6,
    pointsFidelite: 12,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-01-18"),
    updatedAt: new Date("2026-07-15"),
  },
  {
    id: "prod-3",
    reference: "ADI-PRED-EDGE",
    codeBarres: "3600550100013",
    designation: "Adidas Predator Edge FG",
    categorieId: "cat-chaussures",
    fournisseurId: "fournisseur-teamwear",
    marqueId: "marque-adidas",
    prixAchatHT: 70,
    prixAchatTTC: 84,
    prixVenteDetail: 139.99,
    prixVenteDemiGros: 125,
    prixVenteGros: 108,
    tauxTVA: 20,
    quantiteStock: 18,
    stockAlerte: 6,
    unite: "paire",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 4,
    pointsFidelite: 14,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-02-02"),
    updatedAt: new Date("2026-07-22"),
  },
  {
    id: "prod-4",
    reference: "ADI-PRED-ACC3",
    codeBarres: "3600550100014",
    designation: "Adidas Predator Accuracy.3",
    categorieId: "cat-chaussures",
    fournisseurId: "fournisseur-teamwear",
    marqueId: "marque-adidas",
    prixAchatHT: 45,
    prixAchatTTC: 54,
    prixVenteDetail: 89.99,
    prixVenteDemiGros: 79,
    prixVenteGros: 68,
    tauxTVA: 20,
    quantiteStock: 25,
    stockAlerte: 8,
    unite: "paire",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 6,
    pointsFidelite: 9,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-07-10"),
  },
  {
    id: "prod-5",
    reference: "PUMA-FUT-ULT",
    codeBarres: "3600550100015",
    designation: "Puma Future Ultimate FG",
    categorieId: "cat-chaussures",
    fournisseurId: "fournisseur-teamwear",
    marqueId: "marque-puma",
    prixAchatHT: 62,
    prixAchatTTC: 74.4,
    prixVenteDetail: 124.99,
    prixVenteDemiGros: 110,
    prixVenteGros: 95,
    tauxTVA: 20,
    quantiteStock: 15,
    stockAlerte: 5,
    unite: "paire",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 4,
    pointsFidelite: 12,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-02-14"),
    updatedAt: new Date("2026-06-30"),
  },
  {
    id: "prod-6",
    reference: "ON-WHEY-GOLD-227",
    codeBarres: "3600550100016",
    designation: "Whey Gold Standard 2.27kg",
    categorieId: "cat-nutrition-sportive",
    fournisseurId: "fournisseur-nutripro",
    marqueId: "marque-optimum-nutrition",
    prixAchatHT: 38,
    prixAchatTTC: 45.6,
    prixVenteDetail: 69.99,
    prixVenteDemiGros: 62,
    prixVenteGros: 54,
    tauxTVA: 20,
    quantiteStock: 60,
    stockAlerte: 15,
    unite: "boîte",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 12,
    pointsFidelite: 7,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-07-18"),
  },
  {
    id: "prod-7",
    reference: "MP-IMPACT-ISO-250",
    codeBarres: "3600550100017",
    designation: "Whey Impact Isolate 2.5kg",
    categorieId: "cat-nutrition-sportive",
    fournisseurId: "fournisseur-nutripro",
    marqueId: "marque-myprotein",
    prixAchatHT: 32,
    prixAchatTTC: 38.4,
    prixVenteDetail: 59.99,
    prixVenteDemiGros: 53,
    prixVenteGros: 46,
    tauxTVA: 20,
    quantiteStock: 48,
    stockAlerte: 12,
    unite: "boîte",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 12,
    pointsFidelite: 6,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-01-08"),
    updatedAt: new Date("2026-07-05"),
  },
  {
    id: "prod-8",
    reference: "ON-CREA-MONO-500",
    codeBarres: "3600550100018",
    designation: "Créatine Monohydrate 500g",
    categorieId: "cat-nutrition-sportive",
    fournisseurId: "fournisseur-nutripro",
    marqueId: "marque-optimum-nutrition",
    prixAchatHT: 9,
    prixAchatTTC: 10.8,
    prixVenteDetail: 19.99,
    prixVenteDemiGros: 17,
    prixVenteGros: 14,
    tauxTVA: 20,
    quantiteStock: 90,
    stockAlerte: 20,
    unite: "boîte",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 24,
    pointsFidelite: 2,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-01-20"),
    updatedAt: new Date("2026-07-25"),
  },
  {
    id: "prod-9",
    reference: "MP-BCAA-211-400",
    codeBarres: "3600550100019",
    designation: "BCAA 2:1:1 400g",
    categorieId: "cat-nutrition-sportive",
    fournisseurId: "fournisseur-nutripro",
    marqueId: "marque-myprotein",
    prixAchatHT: 12,
    prixAchatTTC: 14.4,
    prixVenteDetail: 24.99,
    prixVenteDemiGros: 21,
    prixVenteGros: 18,
    tauxTVA: 20,
    quantiteStock: 70,
    stockAlerte: 18,
    unite: "boîte",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 24,
    pointsFidelite: 2,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-06-28"),
  },
  {
    id: "prod-10",
    reference: "MP-BAR-CHOC-12",
    codeBarres: "3600550100020",
    designation: "Barre Protéinée Chocolat (carton de 12)",
    categorieId: "cat-nutrition-sportive",
    fournisseurId: "fournisseur-nutripro",
    marqueId: "marque-myprotein",
    prixAchatHT: 14,
    prixAchatTTC: 16.8,
    prixVenteDetail: 26.99,
    prixVenteDemiGros: 23,
    prixVenteGros: 19,
    tauxTVA: 20,
    quantiteStock: 120,
    stockAlerte: 30,
    unite: "carton",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 20,
    pointsFidelite: 3,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-02-06"),
    updatedAt: new Date("2026-07-12"),
  },
  {
    id: "prod-11",
    reference: "ADI-UCL-PRO",
    codeBarres: "3600550100021",
    designation: "Ballon Adidas UCL Pro",
    categorieId: "cat-ballons",
    fournisseurId: "fournisseur-teamwear",
    marqueId: "marque-adidas",
    prixAchatHT: 55,
    prixAchatTTC: 66,
    prixVenteDetail: 109.99,
    prixVenteDemiGros: 96,
    prixVenteGros: 82,
    tauxTVA: 20,
    quantiteStock: 22,
    stockAlerte: 6,
    unite: "pièce",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 6,
    pointsFidelite: 11,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-02-18"),
    updatedAt: new Date("2026-07-08"),
  },
  {
    id: "prod-12",
    reference: "NIKE-FLIGHT",
    codeBarres: "3600550100022",
    designation: "Ballon Nike Flight",
    categorieId: "cat-ballons",
    fournisseurId: "fournisseur-sportidis",
    marqueId: "marque-nike",
    prixAchatHT: 48,
    prixAchatTTC: 57.6,
    prixVenteDetail: 94.99,
    prixVenteDemiGros: 83,
    prixVenteGros: 71,
    tauxTVA: 20,
    quantiteStock: 20,
    stockAlerte: 6,
    unite: "pièce",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 6,
    pointsFidelite: 9,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-02-20"),
    updatedAt: new Date("2026-06-25"),
  },
  {
    id: "prod-13",
    reference: "UHL-ABSGRIP",
    codeBarres: "3600550100023",
    designation: "Gants Gardien Uhlsport Absolutgrip",
    categorieId: "cat-accessoires",
    fournisseurId: "fournisseur-teamwear",
    marqueId: "marque-uhlsport",
    prixAchatHT: 28,
    prixAchatTTC: 33.6,
    prixVenteDetail: 54.99,
    prixVenteDemiGros: 48,
    prixVenteGros: 41,
    tauxTVA: 20,
    quantiteStock: 16,
    stockAlerte: 5,
    unite: "paire",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 4,
    pointsFidelite: 5,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-07-02"),
  },
  {
    id: "prod-14",
    reference: "SEL-GK88",
    codeBarres: "3600550100024",
    designation: "Gants Gardien Select 88",
    categorieId: "cat-accessoires",
    fournisseurId: "fournisseur-teamwear",
    marqueId: "marque-select",
    prixAchatHT: 18,
    prixAchatTTC: 21.6,
    prixVenteDetail: 34.99,
    prixVenteDemiGros: 30,
    prixVenteGros: 26,
    tauxTVA: 20,
    quantiteStock: 0,
    stockAlerte: 5,
    unite: "paire",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 4,
    pointsFidelite: 3,
    disponible: false,
    actif: true,
    createdAt: new Date("2026-03-05"),
    updatedAt: new Date("2026-07-27"),
  },
  {
    id: "prod-15",
    reference: "NIKE-MERC-LITE",
    codeBarres: "3600550100025",
    designation: "Protège-tibias Nike Mercurial Lite",
    categorieId: "cat-accessoires",
    fournisseurId: "fournisseur-sportidis",
    marqueId: "marque-nike",
    prixAchatHT: 8,
    prixAchatTTC: 9.6,
    prixVenteDetail: 17.99,
    prixVenteDemiGros: 15,
    prixVenteGros: 12,
    tauxTVA: 20,
    quantiteStock: 55,
    stockAlerte: 15,
    unite: "paire",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 12,
    pointsFidelite: 1,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-03-10"),
    updatedAt: new Date("2026-06-20"),
  },
  {
    id: "prod-16",
    reference: "ADI-TIRO-SAC",
    codeBarres: "3600550100026",
    designation: "Sac de sport Adidas Tiro",
    categorieId: "cat-accessoires",
    fournisseurId: "fournisseur-teamwear",
    marqueId: "marque-adidas",
    prixAchatHT: 15,
    prixAchatTTC: 18,
    prixVenteDetail: 29.99,
    prixVenteDemiGros: 26,
    prixVenteGros: 22,
    tauxTVA: 20,
    quantiteStock: 34,
    stockAlerte: 10,
    unite: "pièce",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 6,
    pointsFidelite: 3,
    disponible: true,
    actif: true,
    createdAt: new Date("2026-03-15"),
    updatedAt: new Date("2026-07-01"),
  },
  {
    id: "prod-17",
    reference: "NIKE-CHAUSS-FOOT",
    codeBarres: "3600550100027",
    designation: "Chaussettes de football Nike",
    categorieId: "cat-accessoires",
    fournisseurId: "fournisseur-sportidis",
    marqueId: "marque-nike",
    prixAchatHT: 4,
    prixAchatTTC: 4.8,
    prixVenteDetail: 9.99,
    prixVenteDemiGros: 8.5,
    prixVenteGros: 7,
    tauxTVA: 20,
    quantiteStock: 0,
    stockAlerte: 20,
    unite: "paire",
    quantiteMinimumDetail: 1,
    quantiteMinimumGros: 24,
    pointsFidelite: 1,
    disponible: false,
    actif: false,
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-05-30"),
  },
];
