import type { Truck } from "@/types/truck";
import { defaultDepotId } from "@/lib/mock-data/depots";

export const trucks: Truck[] = [
  {
    id: "truck-1",
    code: "CAM-01",
    nom: "Camion 01",
    immatriculation: "78451-A-6",
    marque: "Isuzu",
    modele: "NPR 75",
    annee: 2022,
    capacite: 3500,
    capaciteUnite: "kg",
    statut: "disponible",
    chauffeurId: "driver-1",
    depotId: defaultDepotId,
    kilometrage: 45200,
    dateMiseEnService: new Date("2022-03-15"),
    observations: "",
    actif: true,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-07-20"),
  },
  {
    id: "truck-2",
    code: "CAM-02",
    nom: "Camion 02",
    immatriculation: "34982-B-15",
    marque: "Mitsubishi",
    modele: "Canter FE",
    annee: 2021,
    capacite: 4000,
    capaciteUnite: "kg",
    statut: "en_tournee",
    chauffeurId: "driver-2",
    depotId: defaultDepotId,
    kilometrage: 68900,
    dateMiseEnService: new Date("2021-06-01"),
    observations: "",
    actif: true,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-07-29"),
  },
  {
    id: "truck-3",
    code: "CAM-03",
    nom: "Camion 03",
    immatriculation: "56213-A-1",
    marque: "Fuso",
    modele: "Fighter FK",
    annee: 2019,
    capacite: 12,
    capaciteUnite: "palettes",
    statut: "en_maintenance",
    chauffeurId: "driver-3",
    depotId: defaultDepotId,
    kilometrage: 122400,
    dateMiseEnService: new Date("2019-01-10"),
    observations: "Révision moteur en cours, retour prévu sous 48h.",
    actif: true,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-07-25"),
  },
  {
    id: "truck-4",
    code: "CAM-04",
    nom: "Camion 04",
    immatriculation: "90144-C-20",
    marque: "Iveco",
    modele: "Daily 70C",
    annee: 2023,
    capacite: 2000,
    capaciteUnite: "kg",
    statut: "hors_service",
    chauffeurId: null,
    depotId: defaultDepotId,
    kilometrage: 15300,
    dateMiseEnService: new Date("2023-08-20"),
    observations: "Accident mineur, en attente d'expertise assurance.",
    actif: true,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-07-18"),
  },
  {
    id: "truck-5",
    code: "CAM-05",
    nom: "Camion 05",
    immatriculation: "61027-A-6",
    marque: "Isuzu",
    modele: "FRR 90",
    annee: 2020,
    capacite: 8,
    capaciteUnite: "palettes",
    statut: "disponible",
    chauffeurId: "driver-4",
    depotId: defaultDepotId,
    kilometrage: 95000,
    dateMiseEnService: new Date("2020-11-05"),
    observations: "",
    actif: true,
    createdAt: new Date("2026-02-05"),
    updatedAt: new Date("2026-06-30"),
  },
  {
    id: "truck-6",
    code: "CAM-06",
    nom: "Camion 06",
    immatriculation: "23789-B-9",
    marque: "Mitsubishi",
    modele: "Canter FE",
    annee: 2016,
    capacite: 3000,
    capaciteUnite: "kg",
    statut: "hors_service",
    chauffeurId: null,
    depotId: defaultDepotId,
    kilometrage: 210000,
    dateMiseEnService: new Date("2016-04-12"),
    observations: "Camion retiré de la flotte active.",
    actif: false,
    createdAt: new Date("2026-02-05"),
    updatedAt: new Date("2026-05-10"),
  },
];
